name: 'bark-bot-app'

services:
  bark-bot-db:
    container_name: 'bark-bot-db'
    tty: true
    image: 'postgres:18.2'
    environment:
      - 'POSTGRES_DB=bark-bot-db'
      - 'POSTGRES_USER=${DATASOURCE_USERNAME}'
      - 'POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}'
    ports:
      - '${DATASOURCE_HOST_PORT}:${DATASOURCE_CONTAINER_PORT}'
    volumes:
      - 'bark-bot-db-volume:/var/lib/postgresql'

volumes:
  bark-bot-db-volume: